### ISSUE TITLE
Confusion with "Str" Class Constructor

### ISSUE THREAD

**Issue by plantprogrammer** [supercharge/strings#10]
Could you please explain why you used an || statement with empty quotes in the constructor? Couldn't you just "slice" it?

https://github.com/supercharge/strings/blob/6abd6876205283b9adac2ad4aeeffcf08e0d6aa7/src/str.js#L17

**Comment by marcuspoehls** [comment]
@plantprogrammer Hi Ian, good question!

I used the `||` statement to fall back to an empty string when the given `value` is something like `undefined` or `null`. In those cases, I just want an empty string because of `new String(null)` would result in `'null'` as a string.

```js
// without the || statement
Str(null).get()
// 'null'

// with the || statement
Str(null).get()
// ''
```

Does that make sense and answers your question?
Please don’t hesitate to ask again if anything is unclear. I’m happy to help!

**Comment by plantprogrammer** [comment]
Yep, that makes sense. I'm a beginner programmer, so I failed to account for that situation. Thanks for explaining!

**Comment by marcuspoehls** [comment]
@plantprogrammer Sure, you’re welcome!
