### ISSUE TITLE
Add "kebab", "snake", "pascal" methods

### ISSUE THREAD

**Issue by mcvladthegoat** [supercharge/strings#21]
I want to propose to add new methods: `kebab()`, `snake()`, `pascal()`

**Example**
```js
Str('Supercharge kebab case').kebab().get()
// 'supercharge-kebab-case'

Str('Supercharge snake case').snake().get()
// 'supercharge_snake_case'

Str('Supercharge pascal case').pascal().get()
// 'SuperchargePascalCase'
```

Reference: https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

**Comment by marcuspoehls** [comment]
@mcvladthegoat Good idea Vlad! Do you want to submit a PR for one or all methods?

**Comment by mcvladthegoat** [comment]
@marcuspoehls I want to submit all methods with tests

**Comment by marcuspoehls** [comment]
@mcvladthegoat awesome! Please notice that I moved the code base to TypeScript recently. Mainly because of the type definitions and we don't need to maintain them separately from the code.

Ou already have a fork of this repo. Please update from upstream Vlad. If you need any help, please let me know 😊

**Comment by mcvladthegoat** [comment]
@marcuspoehls ok, thanks :)
I'll update from upstream and push asap

**Comment by marcuspoehls** [comment]
@mcvladthegoat Thank you for your help! Take your time for the PR. I'm happy to review it :)
